### ISSUE TITLE
[QUESTION] Train Your Own Metric

### ISSUE THREAD

**Issue by ecroxford** [Unbabel/COMET#176]
#### What is your question?

I am trying to train my own metric. However, I continue to run into some version of the same problem (Just with a different validation key sometimes). I do not know if this is a bug, dependency issue, or something else. I followed the instructions exactly as stated in a brand virtual environment for this only. My input yaml file is explained below as well. No other files were changed.

#### Code
Yaml file:
regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 16
    train_data: 
      - data/train_mimic.csv
    validation_data: 
      - data/validate_mimic.csv
    hidden_sizes:
      - 2048
      - 1024
    activations: Tanh
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml

Terminal Line: comet-train --cfg configs/models/MIMIC_summ.yaml

Terminal Output: 
usage: comet-train [-h] [--seed_everything SEED_EVERYTHING] [--cfg CFG]
                   [--print_config[=flags]]
                   [--regression_metric.help CLASS_PATH_OR_NAME]
                   [--regression_metric CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--referenceless_regression_metric.help CLASS_PATH_OR_NAME]
                   [--referenceless_regression_metric CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--ranking_metric.help CLASS_PATH_OR_NAME]
                   [--ranking_metric CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--unified_metric.help CLASS_PATH_OR_NAME]
                   [--unified_metric CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--early_stopping.help CLASS_PATH_OR_NAME]
                   [--early_stopping CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--model_checkpoint.help CLASS_PATH_OR_NAME]
                   [--model_checkpoint CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--trainer.help CLASS_PATH_OR_NAME]
                   [--trainer CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                   [--load_from_checkpoint LOAD_FROM_CHECKPOINT]
                   [--strict_load]
error: Parser key "trainer":
  Problem with given class_path 'pytorch_lightning.Trainer':
    Validation failed: No action for key "use_distributed_sampler" to check its value. 

#### What's your environment?
iOS
pip 23.3.1
python 3.11

**Comment by ricardorei** [comment]
This seems like a problem with your Trainer yaml. This sometimes happens when you are using a different pytorch-lightning version where the trainer class as new init args. Please check what version of lightning you have and if the yaml does not have any argument that is not in the [Trainer class](https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api)

**Comment by ecroxford** [comment]
This problem occurs when pytorch-lightning is 1.9.5 and the Trainer yaml does actually have the argument that the original error complains about.

When it is upgraded to 2.1.0 then it results in this error instead:

Seed set to 12
TRAINER ARGUMENTS: 
{
    "accelerator": "cpu",
    "strategy": "ddp",
    "devices": "auto",
    "num_nodes": 1,
    "precision": 16,
    "logger": null,
    "callbacks": [
        {
            "monitor": "val_kendall",
            "min_delta": 0.0,
            "patience": 2,
            "verbose": false,
            "mode": "max",
            "strict": true,
            "check_finite": true,
            "stopping_threshold": null,
            "divergence_threshold": null,
            "wait_count": 0,
            "stopped_epoch": 0,
            "_check_on_train_epoch_end": false,
            "log_rank_zero_only": false,
            "best_score": {}
        },
        {
            "monitor": "val_kendall",
            "verbose": true,
            "save_last": false,
            "save_top_k": 2,
            "save_weights_only": true,
            "auto_insert_metric_name": true,
            "_save_on_train_epoch_end": null,
            "_enable_version_counter": true,
            "_last_global_step_saved": 0,
            "_last_time_checked": null,
            "current_score": null,
            "best_k_models": {},
            "kth_best_model_path": "",
            "best_model_score": null,
            "best_model_path": "",
            "last_model_path": "",
            "_last_checkpoint_saved": "",
            "kth_value": {},
            "mode": "max",
            "_fs": {
                "_cached": true,
                "_intrans": false,
                "_transaction": null,
                "_invalidated_caches_in_transaction": [],
                "dircache": {
                    "_cache": {},
                    "_times": {},
                    "use_listings_cache": true,
                    "listings_expiry_time": null,
                    "max_paths": null
                },
                "_fs_token_": "d7582690d044b51e322c88919146aa6c",
                "auto_mkdir": false,
                "storage_args": [],
                "storage_options": {}
            },
            "dirpath": null,
            "filename": "{epoch}-{step}-{val_kendall:.3f}",
            "_train_time_interval": null,
            "_every_n_epochs": 1,
            "_every_n_train_steps": 0
        },
        {
            "logging_interval": "step",
            "log_momentum": false,
            "log_weight_decay": false,
            "lrs": {},
            "last_momentum_values": {},
            "last_weight_decay_values": {}
        }
    ],
    "fast_dev_run": false,
    "max_epochs": 5,
    "min_epochs": 1,
    "max_steps": -1,
    "min_steps": null,
    "max_time": null,
    "limit_train_batches": 1.0,
    "limit_val_batches": 1.0,
    "limit_test_batches": 1.0,
    "limit_predict_batches": 1.0,
    "overfit_batches": 0,
    "val_check_interval": 1.0,
    "check_val_every_n_epoch": 1,
    "num_sanity_val_steps": 3,
    "log_every_n_steps": 50,
    "enable_checkpointing": null,
    "enable_progress_bar": true,
    "enable_model_summary": true,
    "accumulate_grad_batches": 8,
    "gradient_clip_val": 1.0,
    "gradient_clip_algorithm": "norm",
    "deterministic": false,
    "benchmark": null,
    "inference_mode": true,
    "use_distributed_sampler": true,
    "profiler": null,
    "detect_anomaly": false,
    "barebones": false,
    "plugins": null,
    "sync_batchnorm": false,
    "reload_dataloaders_every_n_epochs": 0,
    "default_root_dir": null
}
/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/lightning_fabric/connector.py:565: `precision=16` is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:557: You passed `Trainer(accelerator='cpu', precision='16-mixed')` but AMP with fp16 is not supported on CPU. Using `precision='bf16-mixed'` instead.
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/setup.py:187: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
MODEL ARGUMENTS: 
{
    "nr_frozen_epochs": 0.3,
    "keep_embeddings_frozen": true,
    "optimizer": "AdamW",
    "encoder_learning_rate": 1e-06,
    "learning_rate": 1.5e-05,
    "layerwise_decay": 0.95,
    "encoder_model": "XLM-RoBERTa",
    "pretrained_model": "xlm-roberta-large",
    "pool": "avg",
    "layer": "mix",
    "layer_transformation": "sparsemax",
    "layer_norm": false,
    "loss": "mse",
    "dropout": 0.1,
    "batch_size": 16,
    "train_data": [
        "data/train_mimic.csv"
    ],
    "validation_data": [
        "data/validate_mimic.csv"
    ],
    "hidden_sizes": [
        2048,
        1024
    ],
    "activations": "Tanh",
    "warmup_steps": 0,
    "final_activation": null,
    "load_pretrained_weights": true
}
Encoder model frozen.
[rank: 0] Seed set to 12
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W ProcessGroupGloo.cpp:725] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------


  | Name                | Type               | Params
-----------------------------------------------------------
0 | encoder             | XLMREncoder        | 558 M 
1 | layerwise_attention | LayerwiseAttention | 26    
2 | train_metrics       | RegressionMetrics  | 0     
3 | val_metrics         | ModuleList         | 0     
4 | estimator           | FeedForward        | 14.7 M
-----------------------------------------------------------
14.7 M    Trainable params
558 M     Non-trainable params
573 M     Total params
2,294.100 Total estimated model params size (MB)
Sanity Checking: |                                        | 0/? [00:00<?, ?it/s]/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:436: Consider setting `persistent_workers=True` in 'val_dataloader' to speed up the dataloader worker initialization.
Traceback (most recent call last):
  File "/Users/ecroxford/Current/COMET/trainComet/bin/comet-train", line 8, in <module>
    sys.exit(train_command())
             ^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/comet/cli/train.py", line 192, in train_command
    trainer.fit(model)
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 112, in run
    self.reset()
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 230, in reset
    iter(data_fetcher)  # creates the iterator inside the fetcher
    ^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/loops/fetchers.py", line 99, in __iter__
    super().__iter__()
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/loops/fetchers.py", line 48, in __iter__
    self.iterator = iter(self.combined_loader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py", line 335, in __iter__
    iter(iterator)
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py", line 144, in __iter__
    self._load_current_iterator()
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py", line 160, in _load_current_iterator
    self.iterators = [iter(self.iterables[self._iterator_idx])]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/Current/COMET/trainComet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1039, in __init__
    w.start()
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/ecroxford/anaconda3/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CometModel.val_dataloader.<locals>.<lambda>'
