### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'scores' when using the model 'Unbabel/wmt22-cometkiwi-da'

### ISSUE THREAD

**Issue by ArchchanaKugathasan** [Unbabel/COMET#186]
## 🐛 Bug

When I try to use the mode **'Unbabel/wmt22-cometkiwi-da'** it pops the following error

Traceback (most recent call last):
  File "/COMETKIWI/main.py", line 19, in <module>
    model_output = model.predict(data, batch_size=8, gpus=1)
  File "Anaconda3/envs/comet/lib/python3.9/site-packages/comet/models/base.py", line 652, in predict
    scores = torch.cat([pred.scores for pred in predictions], dim=0).tolist()
  File "Anaconda3/envs/comet/lib/python3.9/site-packages/comet/models/base.py", line 652, in <listcomp>
    scores = torch.cat([pred.scores for pred in predictions], dim=0).tolist() 

AttributeError: 'dict' object has no attribute 'scores' 

I can see the error is corrected in the repo, but when using the model directly(from huggingface) with the following command, it still shows the error. I think the model needs to be updated too.

**comet-score -s src.txt -t hyp1.txt --model Unbabel/wmt22-cometkiwi-da**

### Environment
OS: [ Linux]
Packaging [conda]

**Comment by ArchchanaKugathasan** [comment]
This issue was sorted when I modified the base.py inside the package installed in conda env

**Comment by Evstrife** [comment]
Is it corrected from huggingface?

**Comment by SimonBenhamou** [comment]
This should also be fixed in [COMET](https://github.com/Unbabel/COMET/tree/master)/[comet](https://github.com/Unbabel/COMET/tree/master/comet)/[models](https://github.com/Unbabel/COMET/tree/master/comet/models)
/predict_writer.py (L89)

**Comment by avidale** [comment]
Can we please reopen this?
Until the PyPI package is not updated, this issue is not really "solved".
