### ISSUE TITLE
mbr-decode triggers an issue with models other than default

### ISSUE THREAD

**Issue by vince62s** [Unbabel/COMET#80]
## 🐛 Bug
works fine with default model.

Encoder model frozen.
Encoding sentences...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 627/627 [00:15<00:00, 40.93it/s]
MBR Scores...:   0%|                                                                                                                                                          | 0/1002 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/comet-mbr", line 8, in <module>
    sys.exit(mbr_command())
  File "/usr/local/lib/python3.8/dist-packages/comet/cli/mbr.py", line 201, in mbr_command
    mbr_matrix = mbr_decoding(src_embeddings, mt_embeddings, model)
  File "/usr/local/lib/python3.8/dist-packages/comet/cli/mbr.py", line 127, in mbr_decoding
    scores = model.estimate(source, translation, pseudo_refs)[
  File "/usr/local/lib/python3.8/dist-packages/comet/models/regression/regression_metric.py", line 186, in estimate
    return {"score": self.estimator(embedded_sequences)}
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/comet/modules/feedforward.py", line 69, in forward
    return self.ff(in_features)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x6144 and 4096x2048)

**Comment by ricardorei** [comment]
@vince62s which model have you tried? I am running it fine with `wmt21-comet-da`

**Comment by ricardorei** [comment]
I think you tried to run MBR with a reference-free model. Reference-free models are not supposed to be used for MBR.

In MBR you will build a matrix where you will compare each hypothesis against each other. The hypothesis with the higher "consensus" is the one that is selected. With a reference-free model, each hypothesis will always be assigned the same score over and over again and the final results would be a simple ranking that does not take into consideration other hypotheses.

**Comment by vince62s** [comment]
Not 100% sure but I think I tried wmt21-comet-mqm too.
